### ISSUE TITLE
PSR-15 ^ 1.0 support

### ISSUE THREAD

**Issue by mneuhaus** [mindplay-dk/middleman#11] opened 2016-12-17 23:06 UTC
Hey,
any chance to get this raised to support 0.3 of PSR-15?

**Comment by mindplay-dk** [comment] 2016-12-18 08:49
0.4 has been tagged now, so that is most likely the next target.

Every minor release of PSR-15 requires a major release of packages such as this one, so I will probably have an unstable release branch first, pending the final approval of PSR-15.

**Comment by fetchandadd** [comment] 2017-01-18 13:46
@mindplay-dk 
If external contribution is wanted, I would provide help to achieve ^0.4 support.

**Comment by mindplay-dk** [comment] 2017-01-18 18:23
@timtegeler thank you - you're welcome to contribute an intermediary patch, as long as you understand this would be installable (for the time being) only using an alias via a named branch.

As long as the proposal is this unstable (lots of discussion going on still) I don't want to do another major release, just so I can do another major release (or possibly several) before PSR-15 is final.

We (my team) also don't want to have to go through several iterations of upgrading our own middleware components and deal with any breaking changes in those, as this would lead to more major releases of our own components.

It's kind of shit situation right now, because PSR-15 is already a cornerstone of our project, but it's still unreliable - we don't have the resources to chase after a moving target right now, so we're going to sit tight until PSR-15 is stable. Release `0.2` works, our middleware components work, our project works, and there's nothing in the latest version that we need as such - until we're done nitpicking about the details, there just isn't much point in upgrading.

That said, we will of course be upgrading as soon PSR-15 is stable.

**Comment by mindplay-dk** [comment] 2017-01-18 18:29
Actually, strike that.

Here's what we can do.

We can open a `3.0.0` release-branch, and leave it open until PSR-15 finalizes, with the understanding that breaking changes may occur before it gets merged.

You can then install the package with an `@` constraint with the exact hash for the time being and upgrade explicitly when it changes and/or becomes final.

How's what? :-)

(and you're of course still welcome to PR, if this is urgent for you, since I don't have the time right now.)

**Comment by fetchandadd** [comment] 2017-01-18 19:42
Ok, I understand your situation. :) 

Your proposal sounds great. And it works for me and so should work for others.

I already have started to implement PSR15 0.4.1 support in a local repo. I'm quite new to PSR15 and your library, but at least the tests are running again. I will link the commit here for further review.

Thank you for your effort.

**Comment by fetchandadd** [comment] 2017-01-18 19:57
Here is the link I mentioned above: 
timtegeler/middleman@45efdee9ff980b73038da25568170487c81a3075

If you create a 3.0.0 release-branch I will provide a PR. I assumed a gitflow-like naming pattern, so I named it in the fork release/3.0.0.

**Comment by mindplay-dk** [comment] 2017-01-18 21:00
Thanks! I will see if I can get to this in the morning :-)

**Comment by fetchandadd** [comment] 2017-01-23 19:06
Do you have any news?

**Comment by mindplay-dk** [comment] 2017-01-24 11:06
Yeah, sorry, I've been preparing a presentation for friday.

I will leave the tab open to remind myself, hopefully I can get to it tomorrow.

**Comment by fetchandadd** [comment] 2017-01-24 11:15
Ok, no problem. There is no need for hurry. Because of your comment, regarding the version of the http-interop/http-middleware dependency, I thought you already finished your review and I could go on with further work or adjustments. Take your time. :)

**Comment by mindplay-dk** [comment] 2017-01-26 08:51
Reviewed and merged your changes to a `3.0.0` branch, which you can now install.

I updated the README and UPGRADING notes as well.

Thank you for the contribution :-)

**Comment by fetchandadd** [comment] 2017-01-26 11:55
You're welcome! :) I tested it in one of my projects. Works like a charm.

**Comment by pavarnos** [comment] 2017-09-28 18:03
any plans for 0.5 support? interested to see how you'd do it

**Comment by mindplay-dk** [comment] 2017-10-04 18:59
Yes, we're trying to slot in the necessary update... should be soon :-)

**Comment by jvriezinga** [comment] 2017-11-14 10:31
Is this something that could help with the move to http-server-middleware? It works fine on my projects using the new interfaces.

[j.vriezinga/middleman@c3316a5](https://github.com/jvriezinga/middleman/commit/c3316a584ec87465a66b3d45d5e34142e96fa052)

**Comment by mindplay-dk** [comment] 2017-11-14 11:25
Yeah, sorry for the delay - we're having some internal planning problems after the organization was internally reorganized. We should be able to prioritize this soon, I hope.

**Comment by jvriezinga** [comment] 2017-11-14 11:45
I see my changes would break PHP 5.x support by requiring `http-interop/http-server-middleware` directly. Should this be swapped for http-interop/http-middleware 0.5 to remain compatible?

Happy to make some changes or assist in any other way that could help

Edit:
Here is one with the minimal changes to support `http-interop/http-middleware` 0.5 and tested on PHP5(.5); [jvriezinga@45efdee](https://github.com/jvriezinga/middleman/commit/4e231e7e2010e024cf0797b66612fdc49512933e)

Edit2:
Here is a branch with the minimal changes to support `http-interop/http-server-middleware` 1.0. This requires PHP7 by design; [jvriezinga@3f7b406](https://github.com/jvriezinga/middleman/commit/3f7b4061a018c60b0e961454a0717977955c02dc). Not sure if this is on the roadmap for 3.0.0 or not.

Let me know by then if there is anything I can do :)

**Comment by mindplay-dk** [comment] 2017-11-15 08:31
@jvriezinga thanks! I'll review your branch when I get to this task.

**Comment by mindplay-dk** [comment] 2017-11-23 10:16
Updates for the PSR-15 `1.0` packages are avaialble in the `3.0.0` branch now.

This means PHP 7 is now required.

**Closed as completed** 2017-12-04 10:21 UTC
